name: "Release"

on:
  push:
    tags:
      - v*

permissions:
  id-token: write
  attestations: write
  contents: write

jobs:
  release:
    uses: wasilibs/actions/.github/workflows/release.yaml@4f1fc34b105780b451ecf7f5bf7834c495f6c23c
    secrets: inherit
